### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/redtide/picom-conf/) for redtide/picom-conf.

### CODE REVIEW

**Comment by stefonarch** [comment]
Ok, sembra andare :)

**Comment by redtide** [comment]
bene!

**Comment by redtide** [comment]
Can I merge this or was just for testing?

**Comment by stefonarch** [comment]
sure, I speak german but no PC-german, but those should be correct.

**Pull request merged**
